version: '3.8'
services:

  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - mscuby
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  events-db:
    image: postgres:alpine
    container_name: events-db
    env_file:
      - ./events/code/.env.${NODE_ENV}
    ports:
      - "5432:5432"
    networks:
      - mscuby

  events-ms:
    container_name: events-ms
    depends_on:
      - events-db
    build: ./events
    volumes:
      - ./events/code:/usr/src/app
    networks:
      - mscuby
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    env_file:
      - ./events/code/.env.${NODE_ENV}
    environment:
      DB_HOST: events-db
    command: bash -c "npm install && npm run dev "
    
networks:
  mscuby:
    driver: bridge