version: '3.8'
services:
  appointments:
    container_name: events
    build: ./events
    volumes:
      - ./events/code:/usr/src/app
    networks:
      - mscuby
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - mscuby
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  users:
    container_name: users
    build: ./users
    volumes:
      - ./users/code:/usr/src/app
    networks:
      - mscuby
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  mscuby:
    driver: bridge