name: Events run

on:
  push:
    branches:
      - dev
      - setup/events-pipeline-58
      - JamineEvents

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start Services
        run: docker-compose up -d 

      - name: Install Dependencies & Run
        run: docker-compose exec -T events-ms npm install

      - name: Check Node Modules
        run: docker-compose exec -T events-ms ls node_modules

      - name: Run Seeder
        run: docker-compose exec -T events-ms npm run test

      - name: Stop Services
        run: docker-compose down
