name: Events run

on:
  push:
    branches:
      - dev
      - setup/events-pipeline-58

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start Services
        run: NODE_ENV=test docker-compose up -d events-db events-ms

      - name: Run Seeder
        run: docker-compose exec events-ms npm run seed

      - name: Stop Services
        run: docker-compose down
